apiVersion: apps/v1
kind: Deployment
metadata:
  name: some-app-server-deployment
spec:
  template:
    spec:
      volumes:
        - name: secrets-store
          csi:
            volumeAttributes:
              # Changing this because the provider class gets renamed per env with a prefix
              secretProviderClass: staging-some-app-server-aws-secrets
      containers:
        - name: some-app-server
          image: ""