name: cd
on:
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      version:
        description: 'The version for the image'
        type: string
        required: true
        default: 'latest'
      registry:
        description: 'The registry where the image repository is.'
        type: string
        required: true
        default: 'FOO_image_registry.foobar-hosters.com'
      repository:
        description: 'The repository name for the image.'
        type: string
        required: true
        default: 'BAR_image_repo'
      deployment-yaml-path:
        description: 'The path to the deployment.yaml file that defines the image used for the container'
        required: true
        type: string
        default: 'kustomize/overlays/dev/deployment.yaml'
jobs:
  cd:
    uses: chippawah/composite-actions/.github/workflows/cd.yaml@main
    with:
      repository: ${{ inputs.repository }}
      version: ${{ inputs.version }}
      registry: ${{ inputs.registry }}
      deployment-yaml-path: ${{ inputs.deployment-yaml-path }}
    secrets:
      COMMIT_TOKEN: ${{ secrets.COMMIT_TOKEN }}