name: output_an_image_name
on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
        default: 'latest'
    outputs:
      tagged_image:
        value: ${{ jobs.set_image_name.outputs.tagged_image }}
jobs:
  set_image_name:
    runs-on: ubuntu-latest
    outputs:
      tagged_image: ${{ steps.set_the_output.tagged_image }}
    steps:
    - name: echo_the_input
      run: "echo 'Input Version: ${{ inputs.version }}'"
    # - name: echo_the_output_file_var
    #   run: "echo 'GITHUB_OUTPUT env var: $GITHUB_OUTPUT'"
    - name: set_the_output
      run: "echo '::set-output name=tagged_image::FOO/BAR:${{ inputs.version }}'"
  echo_previous_job_output:
    runs-on: ubuntu-latest
    needs: set_image_name
    steps:
      - name: echo_the_tagged_image_within_workflow
        run: "echo '\"set_image_name\" job output: ${{ needs.set_image_name.outputs.tagged_image }}'"