name: promote_to_env
on:
  workflow_dispatch:
    inputs:
      base_env:
        required: true
        type: string
        description: 'The base env that will be use to promote from'
        default: 'dev'
      promotion_env:
        description: 'The higher environment that the image will be promoted to.'
        required: true
        type: string
        default: 'staging'
      
jobs:
  promote_image:
    uses: chippawah/composite-actions/.github/workflows/promote-image-to-env.yaml@main
    secrets:
      PR_TOKEN: ${{ secrets.PR_TOKEN }}