name: update_image_in_kustomize
on:
  workflow_call:
    inputs:
      tagged_image:
        required: true
        type: string
        description: 'The full image name including registry, repo, and tag.'
      deployment_yaml_path:
        description: 'The path to the deployment.yaml file that defines the image used for the container'
        required: true
        type: string
        default: 'kustomize/overlays/dev/deployment.yaml'
jobs:
  update_image_in_kustomize:
    runs-on: self-hosted
    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.WORKFLOW_VERSION_BUMP_TOKEN }}
      - name: 'Find and Replace Image Definition'
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: 'image: .*'
          replace: 'image: "${{ inputs.tagged_image }}"'
          include: ${{ inputs.deployment_yaml_path }}
          regex: true
      - name: 'Echo the changed file'
        run: cat test_change_file.yaml