name: update_image_in_kustomize
on:
  workflow_call:
    inputs:
      tagged_image:
        required: true
        type: string
        description: 'The full image name including registry, repo, and tag.'
      deployment_yaml_path:
        description: 'The path to the deployment.yaml file that defines the image used for the container'
        required: true
        type: string
        default: 'test_change_file.yaml'
jobs:
  checkout_the_source_code:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Source Code'
        id: checkout_source_code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.MY_PAT }}
          ref: ${{ github.ref }}
  update_image_in_kustomize:
    needs: checkout_the_source_code
    runs-on: ubuntu-latest
    steps:
      - name: Update the image definition in the YAML
        id: find_and_replace_image
        uses: chippawah/composite-actions/find_and_replace_image@main
        with:
          tagged_image: ${{ inputs.tagged_image }}
          deployment_yaml_path: ${{ inputs.deployment_yaml_path }}
  commit_the_chane:
    needs: update_image_in_kustomize
    runs-on: ubuntu-latest
    steps:
      - name: 'Commit the Change'
        id: commit_the_change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Applies changes to image definition in ${{ inputs.deployment_yaml_path }}"